### ISSUE TITLE
Unable run the example-consumer app

### ISSUE THREAD

**Issue by pratapagiri** [bersling/angular-library-example#2]
I'm unable to run the example-consumer application on Windows 10.

I have download the repo and followed below commands:
**In the 'demo-library' folder** 
(1) yarn
(2)  node duild.js
(3) yarn link

**In the 'example-consumer' folder**
(1) yarn link "libex"
(2) yarn
(3) ng serve

It's giving me the following error:

D:\work\LibSeed\sandbox1\angular-library-example\example-consumer>ng serve
** NG Live Development Server is listening on localhost:4200, open your browser on http://localhost:4200/ **
Date: 2018-02-17T06:57:51.807Z
Hash: 5a66b4efb404bfc7e8c3
Time: 6728ms
chunk {inline} inline.bundle.js (inline) 3.85 kB [entry] [rendered]
chunk {main} main.bundle.js (main) 18 kB [initial] [rendered]
chunk {polyfills} polyfills.bundle.js (polyfills) 548 kB [initial] [rendered]
chunk {styles} styles.bundle.js (styles) 42.2 kB [initial] [rendered]
chunk {vendor} vendor.bundle.js (vendor) 7.42 MB [initial] [rendered]

ERROR in ../demo-library/dist-lib/index.ts
Module build failed: Error: D:\work\LibSeed\sandbox1\angular-library-example\demo-library\dist-lib\index.ts is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.
    at AngularCompilerPlugin.getCompiledFile (D:\work\LibSeed\sandbox1\angular-library-example\example-consumer\node_modules\@ngtools\webpack\src\angular_compiler_plugin.js:677:23)
    at plugin.done.then (D:\work\LibSeed\sandbox1\angular-library-example\example-consumer\node_modules\@ngtools\webpack\src\loader.js:467:39)
    at <anonymous>

Please help me on how do I resolve this issue?

Thanks
Kiran

**Comment by pratapagiri** [comment]
This is issue is resolved when I have used the following:
ng serve --preserve-symlinks
